# Generated by Django 4.1.5 on 2023-01-17 06:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('cafe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cafe',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Coffee', 'Coffee'), ('Food', 'Food'), ('Veggies', 'Veggies'), ('Alcohol', 'Alcohol'), ('Cards', 'Cards')], max_length=150),
        ),
    ]
